org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.42
forge_version_range=[36.2.42,37)
loader_version_range=[36,)
mapping_channel=official
mapping_version=1.16.5

ae2_version=8.4.7
ae2_version_range=[8.4.7,9.0.0)

mod_id=expansionae
mod_name=ExpansionAE
mod_license=LGPL-3.0-or-later
mod_version=0.1.0-dev
mod_group_id=com.bulkcloud.expansionae
mod_authors=BulkCloud0
mod_description=ExpansionAE consolidates selected Applied Energistics 2 addon features into a coherent addon for Minecraft 1.16.5.
